version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-init:
    build: ./server
    depends_on:
      - mongodb
    command: ["node", "mongo-init.js"]

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
      - mongo-init

  client:
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    depends_on:
      - server

volumes:
  mongodb_data:
